name: Download from openload.cc

on: [push, workflow_dispatch]

env:
  FILE_URL: "FILE_URL123"
  FILE_NAME: "FILE_NAME123"
    
jobs:
  build:
  

    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: |
        echo $FILE_URL
        export FILE_URL='HELLO____FILE_URL'
    - name: Test2
      run: echo $FILE_URL

