name: Download from openload.cc

on: [push, workflow_dispatch]

env:
  FILE_URL: ""
  FILE_NAME: ""
  
jobs:

  build:

    runs-on: ubuntu-latest


    steps:
    - name: Download Files
      run: |
        echo 'https://httpbin.org/image' | tee link.txt

        export TMP_URL=`cat link.txt`

        echo 'FILE_URL=$TMP_URL' >> "$GITHUB_ENV"

        echo ${{ env.FILE_URL }}
