name: Download from openload.cc

on: [push, workflow_dispatch]

env:
  FILE_URL: ""
  FILE_NAME: ""

jobs:

  build:

    runs-on: ubuntu-latest


    steps:
    - name: Download Files
      run: |
        curl -s https://openload.cc/c5Dfn7y9zb/Fortify_SCA_23_1_0_Linux_tar_gz | grep -o -E 'https://cdn-.*?"' | cut -d '"' -f 1 | tee link.txt
        export TMP_URL=`cat link.txt`
        echo $TMP_URL
        export TMP_NAME=`echo $TMP_URL | awk -F '/' '{print $NF}'`
        echo $TMP_NAME

        echo FILE_URL=$TMP_URL >> "$GITHUB_ENV"
        echo FILE_NAME=$TMP_NAME >> "$GITHUB_ENV"

    - name: step2
      run: |
        echo ${{ env.FILE_URL }}
        echo ${{ env.FILE_NAME }}
