# Fortify SCA 23.1

# Downloads

# Windows:
# https://openload.cc/t2Jbneydze/Fortify_SCA_23_1_0_Windows_zip

# Mac:
# https://openload.cc/w78fn4y0z8/Fortify_SCA_23_1_0_Mac_tar_gz

# Linux:
# https://openload.cc/c5Dfn7y9zb/Fortify_SCA_23_1_0_Linux_tar_gz

# Crack & License file:
# https://openload.cc/J6Hfn3y8z1/fortify_sca_23_1_crack_pwn3rzs_cyberarsenal_7z
# https://bayfiles.com/ReHbnbyezf/fortify_sca_23_1_crack_pwn3rzs_cyberarsenal_7z

# Rules:
# https://openload.cc/F2ubL2y1z9/rules2023_zip

# Password: Pwn3rzs


# Setup:
# Follow README.txt
# (REMEMBER TO PUT fortify.license IN SAME PATH OF INSTALLER)

# This new version of Fortify SCA has split the UI tools from the installer and made it CLI only.
# To understand how to use it, refer to the user guide online or the documentation inside installer archives.

# Enjoy!




name: Download from openload.cc

on: [push, workflow_dispatch]

env:
  DOWN_PAGE: "https://openload.cc/t2Jbneydze/Fortify_SCA_23_1_0_Windows_zip"
  FILE_URL: ""
  FILE_NAME: ""

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download Files
      run: |
        curl -s ${{ env.DOWN_PAGE }} | grep -o -E 'https://cdn-.*?"' | cut -d '"' -f 1 | tee link.txt
        export TMP_URL=`cat link.txt`
        export TMP_NAME=`echo $TMP_URL | awk -F '/' '{print $NF}'`
        wget -O $TMP_NAME $TMP_URL

        echo FILE_URL=$TMP_URL >> "$GITHUB_ENV"
        echo FILE_NAME=$TMP_NAME >> "$GITHUB_ENV"
    
    - name: Upload Files
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.FILE_NAME }}
        path: ${{ env.FILE_NAME }}

