

name: Download from openload.cc

on: [push, workflow_dispatch]

env:
  DOWN_PAGE: "https://openload.cc/Jej8K41ez7/Acunetix_v23_6_Windows_Pwn3rzs_CyberArsenal_rar"
  FILE_URL: ""
  FILE_NAME: ""


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download Files
      run: |
        curl -s ${{ env.DOWN_PAGE }} | grep -o -E 'https://cdn-.*?"' | cut -d '"' -f 1 | tee link.txt
        export TMP_URL=`cat link.txt`
        export TMP_NAME=`echo $TMP_URL | awk -F '/' '{print $NF}'`
        wget -O $TMP_NAME $TMP_URL

        echo FILE_URL=$TMP_URL >> "$GITHUB_ENV"
        echo FILE_NAME=$TMP_NAME >> "$GITHUB_ENV"
    
    - name: Upload Files
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.FILE_NAME }}
        path: ${{ env.FILE_NAME }}

