name: Download from openload.cc

on: [push, workflow_dispatch]

env:
  FILE_URL: ""
  FILE_NAME: ""
    
jobs:
  build:
  

    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: |
        echo 123123 > link.txt
        cat link.txt > $FILE_URL
        echo $FILE_URL
    - name: Test2
      run: echo $FILE_URL

