name: Download from openload.cc

on: [push, workflow_dispatch]

env:
  FILE_URL: ""
  FILE_NAME: ""
  
jobs:

  build:

    runs-on: ubuntu-latest


    steps:
    - name: Download Files
      run: |
        curl -s https://openload.cc/c5Dfn7y9zb/Fortify_SCA_23_1_0_Linux_tar_gz | grep -o -E 'https://cdn-.*?"' | cut -d '"' -f 1 | tee link.txt
        echo "FILE_URL=`cat link.txt`" >> "$GITHUB_ENV"
        export TMP_URL=${{ env.FILE_URL }}
        echo $TMP_URL
