name: Download from openload.cc

on: [push, workflow_dispatch]

env:
  FILE_URL: "FILE_URL123"
  FILE_NAME: "FILE_NAME123"
    
jobs:
  build:
  

    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: |
        echo ${{ env.FILE_URL }}
        echo "FILE_URL=HELLO____FILE_URL" >> "$GITHUB_ENV"
    - name: Test2
      run: echo ${{ env.FILE_URL }}

