name: Download from openload.cc

on: [push, workflow_dispatch]

  
jobs:

  build:

    runs-on: ubuntu-latest


    steps:
    - name: Download Files
      run: |
        curl -s https://openload.cc/c5Dfn7y9zb/Fortify_SCA_23_1_0_Linux_tar_gz | grep -o -E 'https://cdn-.*?"' | cut -d '"' -f 1 | tee link.txt
        export TMP_URL=`cat link.txt`
        echo $TMP_URL
        echo FILE_URL=$TMP_URL >> "$GITHUB_ENV"
        echo ${{ env.FILE_URL }}

    - name: step2
      run: |
        echo ${{ env.FILE_URL }}

